(ns dwdm_system.actor
  "dwdm_system clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). DWDM optical line system / 光電融合 transport.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; DwdmSystem
   {:db/ident :dwdm_system.DwdmSystem/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dwdm_system.DwdmSystem/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.DwdmSystem/bandPlan :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.DwdmSystem/channels :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.DwdmSystem/capacityTbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.DwdmSystem/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.DwdmSystem/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; OpticalChannel
   {:db/ident :dwdm_system.OpticalChannel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dwdm_system.OpticalChannel/systemId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.OpticalChannel/lambdaNm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.OpticalChannel/dataRateGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.OpticalChannel/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.OpticalChannel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.OpticalChannel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Amplifier
   {:db/ident :dwdm_system.Amplifier/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dwdm_system.Amplifier/systemId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Amplifier/type :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Amplifier/gainDb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Amplifier/noiseFigureDb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Amplifier/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Amplifier/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Roadm
   {:db/ident :dwdm_system.Roadm/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dwdm_system.Roadm/systemId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Roadm/degree :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Roadm/technology :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Roadm/addDropPorts :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Roadm/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Roadm/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Span
   {:db/ident :dwdm_system.Span/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dwdm_system.Span/systemId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Span/lengthKm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Span/fiberType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Span/lossDb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Span/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.Span/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; SupervisoryChannel
   {:db/ident :dwdm_system.SupervisoryChannel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dwdm_system.SupervisoryChannel/systemId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.SupervisoryChannel/lambdaNm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.SupervisoryChannel/protocol :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.SupervisoryChannel/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.SupervisoryChannel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dwdm_system.SupervisoryChannel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"DwdmSystem" "OpticalChannel" "Amplifier" "Roadm" "Span" "SupervisoryChannel"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "dwdm_system: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "dwdm_system: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "dwdm_system: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── DwdmSystem ────────────────────────────────────────────────────────────────
(defn create-dwdm-system
  "Create a DwdmSystem."
  [port data]
  (require-fields data ["name" "bandPlan"])
  (let [id (new-id "dwd_dwd")
        e {:db/id id
           :dwdm_system.DwdmSystem/id id
           :dwdm_system.DwdmSystem/name (get data :name)
           :dwdm_system.DwdmSystem/bandPlan (get data :bandPlan)
           :dwdm_system.DwdmSystem/channels (as-long (get data :channels))
           :dwdm_system.DwdmSystem/capacityTbps (as-double (get data :capacityTbps))
           :dwdm_system.DwdmSystem/createdAt (now)
           :dwdm_system.DwdmSystem/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-dwdm-systems
  "List DwdmSystem with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-dwdm-systems port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dwdm_system.DwdmSystem/id))
         rows (apply-filters rows (:filter opts) [:dwdm_system.DwdmSystem/name :dwdm_system.DwdmSystem/bandPlan :dwdm_system.DwdmSystem/channels :dwdm_system.DwdmSystem/capacityTbps])]
     (paginate rows opts))))

(defn get-dwdm-system
  "Retrieve a DwdmSystem by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-dwdm-system port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-dwdm-system
  "Update a DwdmSystem; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :dwdm_system.DwdmSystem/name (get data :name)]))
                   (cond-> (contains? data :bandPlan) (conj [:db/add id :dwdm_system.DwdmSystem/bandPlan (get data :bandPlan)]))
                   (cond-> (contains? data :channels) (conj [:db/add id :dwdm_system.DwdmSystem/channels (as-long (get data :channels))]))
                   (cond-> (contains? data :capacityTbps) (conj [:db/add id :dwdm_system.DwdmSystem/capacityTbps (as-double (get data :capacityTbps))]))
                   (conj [:db/add id :dwdm_system.DwdmSystem/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-dwdm-system
  "Delete a DwdmSystem."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── OpticalChannel ────────────────────────────────────────────────────────────────
(defn create-optical-channel
  "Create a OpticalChannel."
  [port data]
  (require-fields data ["lambdaNm" "dataRateGbps"])
  (let [id (new-id "dwd_opt")
        e {:db/id id
           :dwdm_system.OpticalChannel/id id
           :dwdm_system.OpticalChannel/systemId (get data :systemId)
           :dwdm_system.OpticalChannel/lambdaNm (as-double (get data :lambdaNm))
           :dwdm_system.OpticalChannel/dataRateGbps (as-double (get data :dataRateGbps))
           :dwdm_system.OpticalChannel/status (get data :status)
           :dwdm_system.OpticalChannel/createdAt (now)
           :dwdm_system.OpticalChannel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-optical-channels
  "List OpticalChannel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-optical-channels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dwdm_system.OpticalChannel/id))
         rows (apply-filters rows (:filter opts) [:dwdm_system.OpticalChannel/systemId :dwdm_system.OpticalChannel/lambdaNm :dwdm_system.OpticalChannel/dataRateGbps :dwdm_system.OpticalChannel/status])]
     (paginate rows opts))))

(defn get-optical-channel
  "Retrieve a OpticalChannel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-optical-channel port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-optical-channel
  "Update a OpticalChannel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :systemId) (conj [:db/add id :dwdm_system.OpticalChannel/systemId (get data :systemId)]))
                   (cond-> (contains? data :lambdaNm) (conj [:db/add id :dwdm_system.OpticalChannel/lambdaNm (as-double (get data :lambdaNm))]))
                   (cond-> (contains? data :dataRateGbps) (conj [:db/add id :dwdm_system.OpticalChannel/dataRateGbps (as-double (get data :dataRateGbps))]))
                   (cond-> (contains? data :status) (conj [:db/add id :dwdm_system.OpticalChannel/status (get data :status)]))
                   (conj [:db/add id :dwdm_system.OpticalChannel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-optical-channel
  "Delete a OpticalChannel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Amplifier ────────────────────────────────────────────────────────────────
(defn create-amplifier
  "Create a Amplifier."
  [port data]
  (require-fields data ["type" "gainDb"])
  (let [id (new-id "dwd_amp")
        e {:db/id id
           :dwdm_system.Amplifier/id id
           :dwdm_system.Amplifier/systemId (get data :systemId)
           :dwdm_system.Amplifier/type (get data :type)
           :dwdm_system.Amplifier/gainDb (as-double (get data :gainDb))
           :dwdm_system.Amplifier/noiseFigureDb (as-double (get data :noiseFigureDb))
           :dwdm_system.Amplifier/createdAt (now)
           :dwdm_system.Amplifier/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-amplifiers
  "List Amplifier with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-amplifiers port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dwdm_system.Amplifier/id))
         rows (apply-filters rows (:filter opts) [:dwdm_system.Amplifier/systemId :dwdm_system.Amplifier/type :dwdm_system.Amplifier/gainDb :dwdm_system.Amplifier/noiseFigureDb])]
     (paginate rows opts))))

(defn get-amplifier
  "Retrieve a Amplifier by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-amplifier port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-amplifier
  "Update a Amplifier; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :systemId) (conj [:db/add id :dwdm_system.Amplifier/systemId (get data :systemId)]))
                   (cond-> (contains? data :type) (conj [:db/add id :dwdm_system.Amplifier/type (get data :type)]))
                   (cond-> (contains? data :gainDb) (conj [:db/add id :dwdm_system.Amplifier/gainDb (as-double (get data :gainDb))]))
                   (cond-> (contains? data :noiseFigureDb) (conj [:db/add id :dwdm_system.Amplifier/noiseFigureDb (as-double (get data :noiseFigureDb))]))
                   (conj [:db/add id :dwdm_system.Amplifier/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-amplifier
  "Delete a Amplifier."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Roadm ────────────────────────────────────────────────────────────────
(defn create-roadm
  "Create a Roadm."
  [port data]
  (require-fields data ["degree" "technology"])
  (let [id (new-id "dwd_roa")
        e {:db/id id
           :dwdm_system.Roadm/id id
           :dwdm_system.Roadm/systemId (get data :systemId)
           :dwdm_system.Roadm/degree (as-long (get data :degree))
           :dwdm_system.Roadm/technology (get data :technology)
           :dwdm_system.Roadm/addDropPorts (as-long (get data :addDropPorts))
           :dwdm_system.Roadm/createdAt (now)
           :dwdm_system.Roadm/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-roadms
  "List Roadm with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-roadms port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dwdm_system.Roadm/id))
         rows (apply-filters rows (:filter opts) [:dwdm_system.Roadm/systemId :dwdm_system.Roadm/degree :dwdm_system.Roadm/technology :dwdm_system.Roadm/addDropPorts])]
     (paginate rows opts))))

(defn get-roadm
  "Retrieve a Roadm by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-roadm port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-roadm
  "Update a Roadm; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :systemId) (conj [:db/add id :dwdm_system.Roadm/systemId (get data :systemId)]))
                   (cond-> (contains? data :degree) (conj [:db/add id :dwdm_system.Roadm/degree (as-long (get data :degree))]))
                   (cond-> (contains? data :technology) (conj [:db/add id :dwdm_system.Roadm/technology (get data :technology)]))
                   (cond-> (contains? data :addDropPorts) (conj [:db/add id :dwdm_system.Roadm/addDropPorts (as-long (get data :addDropPorts))]))
                   (conj [:db/add id :dwdm_system.Roadm/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-roadm
  "Delete a Roadm."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Span ────────────────────────────────────────────────────────────────
(defn create-span
  "Create a Span."
  [port data]
  (require-fields data ["lengthKm" "fiberType"])
  (let [id (new-id "dwd_spa")
        e {:db/id id
           :dwdm_system.Span/id id
           :dwdm_system.Span/systemId (get data :systemId)
           :dwdm_system.Span/lengthKm (as-double (get data :lengthKm))
           :dwdm_system.Span/fiberType (get data :fiberType)
           :dwdm_system.Span/lossDb (as-double (get data :lossDb))
           :dwdm_system.Span/createdAt (now)
           :dwdm_system.Span/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-spans
  "List Span with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-spans port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dwdm_system.Span/id))
         rows (apply-filters rows (:filter opts) [:dwdm_system.Span/systemId :dwdm_system.Span/lengthKm :dwdm_system.Span/fiberType :dwdm_system.Span/lossDb])]
     (paginate rows opts))))

(defn get-span
  "Retrieve a Span by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-span port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-span
  "Update a Span; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :systemId) (conj [:db/add id :dwdm_system.Span/systemId (get data :systemId)]))
                   (cond-> (contains? data :lengthKm) (conj [:db/add id :dwdm_system.Span/lengthKm (as-double (get data :lengthKm))]))
                   (cond-> (contains? data :fiberType) (conj [:db/add id :dwdm_system.Span/fiberType (get data :fiberType)]))
                   (cond-> (contains? data :lossDb) (conj [:db/add id :dwdm_system.Span/lossDb (as-double (get data :lossDb))]))
                   (conj [:db/add id :dwdm_system.Span/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-span
  "Delete a Span."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── SupervisoryChannel ────────────────────────────────────────────────────────────────
(defn create-supervisory-channel
  "Create a SupervisoryChannel."
  [port data]
  (require-fields data ["lambdaNm" "protocol"])
  (let [id (new-id "dwd_sup")
        e {:db/id id
           :dwdm_system.SupervisoryChannel/id id
           :dwdm_system.SupervisoryChannel/systemId (get data :systemId)
           :dwdm_system.SupervisoryChannel/lambdaNm (as-double (get data :lambdaNm))
           :dwdm_system.SupervisoryChannel/protocol (get data :protocol)
           :dwdm_system.SupervisoryChannel/status (get data :status)
           :dwdm_system.SupervisoryChannel/createdAt (now)
           :dwdm_system.SupervisoryChannel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-supervisory-channels
  "List SupervisoryChannel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-supervisory-channels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dwdm_system.SupervisoryChannel/id))
         rows (apply-filters rows (:filter opts) [:dwdm_system.SupervisoryChannel/systemId :dwdm_system.SupervisoryChannel/lambdaNm :dwdm_system.SupervisoryChannel/protocol :dwdm_system.SupervisoryChannel/status])]
     (paginate rows opts))))

(defn get-supervisory-channel
  "Retrieve a SupervisoryChannel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-supervisory-channel port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-supervisory-channel
  "Update a SupervisoryChannel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :systemId) (conj [:db/add id :dwdm_system.SupervisoryChannel/systemId (get data :systemId)]))
                   (cond-> (contains? data :lambdaNm) (conj [:db/add id :dwdm_system.SupervisoryChannel/lambdaNm (as-double (get data :lambdaNm))]))
                   (cond-> (contains? data :protocol) (conj [:db/add id :dwdm_system.SupervisoryChannel/protocol (get data :protocol)]))
                   (cond-> (contains? data :status) (conj [:db/add id :dwdm_system.SupervisoryChannel/status (get data :status)]))
                   (conj [:db/add id :dwdm_system.SupervisoryChannel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-supervisory-channel
  "Delete a SupervisoryChannel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/dwdmsystems" :op :create :entity "DwdmSystem"}
   {:method "GET" :path "/v1/dwdmsystems" :op :list :entity "DwdmSystem"}
   {:method "GET" :path "/v1/dwdmsystems/:id" :op :get :entity "DwdmSystem"}
   {:method "PATCH" :path "/v1/dwdmsystems/:id" :op :update :entity "DwdmSystem"}
   {:method "DELETE" :path "/v1/dwdmsystems/:id" :op :delete :entity "DwdmSystem"}
   {:method "POST" :path "/v1/opticalchannels" :op :create :entity "OpticalChannel"}
   {:method "GET" :path "/v1/opticalchannels" :op :list :entity "OpticalChannel"}
   {:method "GET" :path "/v1/opticalchannels/:id" :op :get :entity "OpticalChannel"}
   {:method "PATCH" :path "/v1/opticalchannels/:id" :op :update :entity "OpticalChannel"}
   {:method "DELETE" :path "/v1/opticalchannels/:id" :op :delete :entity "OpticalChannel"}
   {:method "POST" :path "/v1/amplifiers" :op :create :entity "Amplifier"}
   {:method "GET" :path "/v1/amplifiers" :op :list :entity "Amplifier"}
   {:method "GET" :path "/v1/amplifiers/:id" :op :get :entity "Amplifier"}
   {:method "PATCH" :path "/v1/amplifiers/:id" :op :update :entity "Amplifier"}
   {:method "DELETE" :path "/v1/amplifiers/:id" :op :delete :entity "Amplifier"}
   {:method "POST" :path "/v1/roadms" :op :create :entity "Roadm"}
   {:method "GET" :path "/v1/roadms" :op :list :entity "Roadm"}
   {:method "GET" :path "/v1/roadms/:id" :op :get :entity "Roadm"}
   {:method "PATCH" :path "/v1/roadms/:id" :op :update :entity "Roadm"}
   {:method "DELETE" :path "/v1/roadms/:id" :op :delete :entity "Roadm"}
   {:method "POST" :path "/v1/spans" :op :create :entity "Span"}
   {:method "GET" :path "/v1/spans" :op :list :entity "Span"}
   {:method "GET" :path "/v1/spans/:id" :op :get :entity "Span"}
   {:method "PATCH" :path "/v1/spans/:id" :op :update :entity "Span"}
   {:method "DELETE" :path "/v1/spans/:id" :op :delete :entity "Span"}
   {:method "POST" :path "/v1/supervisorychannels" :op :create :entity "SupervisoryChannel"}
   {:method "GET" :path "/v1/supervisorychannels" :op :list :entity "SupervisoryChannel"}
   {:method "GET" :path "/v1/supervisorychannels/:id" :op :get :entity "SupervisoryChannel"}
   {:method "PATCH" :path "/v1/supervisorychannels/:id" :op :update :entity "SupervisoryChannel"}
   {:method "DELETE" :path "/v1/supervisorychannels/:id" :op :delete :entity "SupervisoryChannel"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"dwdmsystems" {:create create-dwdm-system :list list-dwdm-systems :get get-dwdm-system :update update-dwdm-system :delete delete-dwdm-system}
   "opticalchannels" {:create create-optical-channel :list list-optical-channels :get get-optical-channel :update update-optical-channel :delete delete-optical-channel}
   "amplifiers" {:create create-amplifier :list list-amplifiers :get get-amplifier :update update-amplifier :delete delete-amplifier}
   "roadms" {:create create-roadm :list list-roadms :get get-roadm :update update-roadm :delete delete-roadm}
   "spans" {:create create-span :list list-spans :get get-span :update update-span :delete delete-span}
   "supervisorychannels" {:create create-supervisory-channel :list list-supervisory-channels :get get-supervisory-channel :update update-supervisory-channel :delete delete-supervisory-channel}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "dwdm_system-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
